import {
	CamelCasePlugin,
	type ColumnType,
	type GeneratedAlways,
	Kysely,
} from "kysely";
import { D1Dialect } from "kysely-d1";

/**
 * An only updatable column type for Kysely.
 * This type prevents inserts to the column.
 *
 * This is useful for columns that are generated by the database on insert,
 * but can be updated later.
 * @example
 * type OnlyUpdatableString = OnlyUpdatable<string>;
 */
type OnlyUpdatable<T> = ColumnType<T, never, T>;

type Immutable<T> = ColumnType<T, T, never>;

export interface T_Body {
	/**
	 * Auto-incremented ID of the body.
	 * @private
	 */
	id: GeneratedAlways<number>;
	/**
	 * Public ID in the format of NanoID.
	 * @public
	 */
	publicId: Immutable<string>;
	/**
	 * Name of the body.
	 * @public
	 */
	name: string;
	/**
	 * ID of the user who owns this body.
	 * @private
	 */
	userId: Immutable<string>;
}

export interface T_FilmStock {
	/**
	 * Auto-incremented ID of the film stock.
	 * @private
	 */
	id: GeneratedAlways<number>;
	/**
	 * Public ID in the format of NanoID.
	 * @public
	 */
	publicId: Immutable<string>;
	/**
	 * Name of the film stock.
	 * @public
	 */
	name: string;
	/**
	 * ID of the user who owns this film stock.
	 * @private
	 */
	userId: Immutable<string>;
}

export interface T_Lens {
	/**
	 * Auto-incremented ID of the lens.
	 * @private
	 */
	id: GeneratedAlways<number>;
	/**
	 * Public ID in the format of NanoID.
	 * @public
	 */
	publicId: Immutable<string>;
	/**
	 * Name of the lens.
	 */
	name: string;
	/**
	 * ID of the user who owns this lens.
	 * @private
	 */
	userId: Immutable<string>;
}

export interface T_Roll {
	/**
	 * Auto-incremented ID of the roll.
	 * @private
	 */
	id: GeneratedAlways<number>;
	/**
	 * Public ID in the format of NanoID.
	 * @public
	 */
	publicId: Immutable<string>;
	/**
	 * Alias for the roll.
	 * @public
	 */
	alias: string | null;
	/**
	 * Expects ISO date string.
	 * @public
	 * @example "2023-10-05T14:48:00.000Z"
	 */
	loadedAt: GeneratedAlways<string>;
	/**
	 * Expects ISO date string
	 * @public
	 * @example "2023-10-20T10:30:00.000Z"
	 */
	finishedAt: OnlyUpdatable<string | null>;
	/**
	 * ID of the body used in this roll.
	 * @private
	 */
	bodyId: number;
	/**
	 * ID of the film stock used in this roll.
	 * @private
	 */
	filmStockId: number;
	/**
	 * ID of the user who owns this roll.
	 * @private
	 */
	userId: Immutable<string>;
}

export interface T_Frame {
	/**
	 * Auto-incremented ID of the frame.
	 * @private
	 */
	id: GeneratedAlways<number>;
	/**
	 * Public ID in the format of NanoID.
	 * @public
	 */
	publicId: Immutable<string>;
	/**
	 * Expects ISO date string
	 * @public
	 * @example "2023-10-10T12:00:00.000Z"
	 */
	shotAt: OnlyUpdatable<string>;
	/**
	 * ID of the roll this frame belongs to.
	 * @private
	 */
	rollId: number;
	/**
	 * ID of the lens used to take this frame.
	 * @private
	 */
	lensId: number;
	/**
	 * ID of the user who owns this frame.
	 * @private
	 */
	userId: Immutable<string>;
}

type Database = {
	film_stock: T_FilmStock;
	body: T_Body;
	lens: T_Lens;
	roll: T_Roll;
	frame: T_Frame;
};

/**
 * Create a Kysely database instance connected to the D1 database.
 * @param env - The Cloudflare environment containing the D1 database.
 * @returns A Kysely instance connected to the D1 database.
 * @example
 * export const loader = async ({ context }: Route.LoaderArgs) => {
 *   const db = getDbInstance(context.cloudflare.env);
 *   const res = await db.selectFrom("film_stock").selectAll().execute();
 *   return res;
 * }
 */
export const getDbInstance = (env: Env) => {
	return new Kysely<Database>({
		dialect: new D1Dialect({ database: env.odpt_challenge }),
		plugins: [new CamelCasePlugin()],
	});
};

export type DBInstance = ReturnType<typeof getDbInstance>;
